[platformio]
default_envs = cardputer

[env]
platform = espressif32@^6.9.0
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
  -D CORE_DEBUG_LEVEL=1
lib_deps =
  m5stack/M5Unified@^0.2.5

[env:cardputer]
board = m5stack-cardputer
build_flags =
  ${env.build_flags}
  -D WIGGLES_CARDPUTER=1

[env:cores3]
board = m5stack-cores3
build_flags =
  ${env.build_flags}
  -D WIGGLES_CORES3=1
